dist: xenial
language: python
python:
- "3.6"
- "3.7"
- "3.8-dev"
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install codecov
- python .setup/make_initial_config_file.py > config.py
script:
- nosetests
- coverage run -m nose
after_success:
- coveralls
- codecov
